export const ADMIN_LOGIN_REQUEST = 'ADMIN_LOGIN_REQUEST';
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS';
export const ADMIN_LOGIN_FAIL = 'ADMIN_LOGIN_FAIL';
export const ADMIN_LOGOUT = 'ADMIN_LOGOUT';

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_FAIL = 'USER_LIST_FAIL';

export const CONFIRM_CREATE_REQUEST = 'CONFIRM_CREATE_REQUEST'
export const CONFIRM_CREATE_SUCCESS = 'CONFIRM_CREATE_SUCCESS'
export const CONFIRM_CREATE_FAIL = 'CONFIRM_CREATE_FAIL'
export const CONFIRM_CREATE_RESET = 'CONFIRM_CREATE_RESET'